/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/**
 * Supabase 프로젝트 정보
 * 
 * 환경 변수에서 먼저 읽고, 없으면 기본값 사용
 * 환경 변수 설정 방법:
 * - Vite: .env 파일에 VITE_SUPABASE_PROJECT_ID, VITE_SUPABASE_ANON_KEY 추가
 * - 프로덕션: 빌드 시스템의 환경 변수로 주입
 * 
 * ⚠️ 주의: publicAnonKey는 클라이언트에 노출되어도 안전합니다 (RLS로 보호됨)
 * 하지만 GitHub에 커밋하지 않으려면 환경 변수를 사용하세요.
 */

// 환경 변수에서 값 읽기 (Vite 환경)
const getEnvVar = (key: string, fallback: string): string => {
  // Vite 환경 변수
  const value = import.meta.env[key];
  return value || fallback;
};

export const projectId = getEnvVar(
  'VITE_SUPABASE_PROJECT_ID',
  ''
);

export const publicAnonKey = getEnvVar(
  'VITE_SUPABASE_ANON_KEY',
  ''
);

